# Generated by Django 3.2.8 on 2024-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_submission_problem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='problem_content',
            field=models.CharField(default='No description!', max_length=1000),
        ),
    ]
