# Generated by Django 3.2.8 on 2024-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='problem_name',
            field=models.CharField(max_length=50),
        ),
    ]
